[build]
  publish = "packages/front-end/build/"
  command = "yarn -v && yarn build"
  base = "/"

[build.environment]
  NODE_ENV = "production"
  YARN_VERSION = "1.22.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200