[build]
  publish = "packages/front-end/build/"
  command = "yarn -v && exit 1"
  base = "/"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200