service: shop-backend

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-domain-manager

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: prd

custom:
  customDomain:
    domainName: api.javascript.kiwi
    basePath: ""
    hostedZoneId: Z07130781UYYC1ZGE6N6M
    stage: ${self:provider.stage}
    certificateName: api.javascript.kiwi
    createRoute53Record: true

functions:
  backend:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /refresh_token
          method: ANY
      - http:
          path: /graphql
          method: ANY
