service: shop-backend

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:NODE_ENV}

functions:
  backend:
    handler: lambda.backend
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /refresh_token
          method: ANY
      - http:
          path: /graphql
          method: ANY
