service: shop-backend

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: prd

functions:
  backend:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /refresh_token
          method: ANY
      - http:
          path: /graphql
          method: ANY
