service: shop-backend

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}

functions:
  backend:
    handler: lambda.backend
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /refresh_token
          method: ANY
          cors: true
      - http:
          path: /graphql
          method: ANY
          cors: true
